
database:
  name: oauth-test
  username: # set up username for database
  password: # set up username password for database
  host: localhost
  port: 5432

client:
  id: # set up your client_id
  secret: # set up your client_secret

redirect:
  url: http://localhost:8080/login

